
import Navbar from "@/components/common/navbar";
import "./globals.css";
import Footer from "@/components/common/footer";
import MainLayout from "@/components/layouts/MainLayout";




export const metadata = {
  title: "Royal Plams Hotel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
      
        <Navbar/>
        <MainLayout>
        <div className="min-h-screen bg-resort-bg bg-cover bg-center bg-no-repeat">
        <div className="bg-white/10 min-h-screen">{children}</div>
        </div>
       
      
        <Footer/> 
        </MainLayout>
      </body>
    </html>
  );
}

